name = "T4APartitionedTT"
uuid = "7ada5264-53d5-494a-9572-4199565888e0"
authors = ["Hiroshi Shinaoka <h.shinaoka@gmail.com> and contributors"]
version = "0.8.0"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
EllipsisNotation = "da5c29d0-fa7d-589e-88eb-ea29b0a81949"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
T4AITensorCompat = "864b39ca-388c-4f43-a593-a1076cf4b253"

[compat]
Distributed = "1"
EllipsisNotation = "1"
OrderedCollections = "1.6.3"
TensorCrossInterpolation = "0.9.18"
T4AITensorCompat = "0.8"

[extras]
QuanticsGrids = "634c7f73-3e90-4749-a1bd-001b8efc642d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
TensorCrossInterpolation = "b261b2ec-6378-4871-b32e-9173bb050604"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random", "TensorCrossInterpolation", "QuanticsGrids"]
