[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
QuanticsGrids = "634c7f73-3e90-4749-a1bd-001b8efc642d"
T4AITensorCompat = "864b39ca-388c-4f43-a593-a1076cf4b253"
T4APartitionedTT = "7ada5264-53d5-494a-9572-4199565888e0"
T4AQuanticsTCI = "ef09ec98-57a2-49a0-bf0b-86b55a3d9051"
T4ATensorCI = "14428447-6903-48c7-83df-f2cb08af9918"

[compat]
T4AITensorCompat = "0.8"
